name: Publicar Contratos Automáticamente

on:
  push:
    branches:
      - tooling
    paths:
      - 'src/contracts/**' # Se dispara solo si cambia algo aquí dentro

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Descargar código fuente
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Descarga todo el historial para poder hacer push del tag

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://github.com'
          scope: '@mauedgar'

      - name: Configurar Git para versionado
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Incrementar versión del paquete
        # Incrementa el último número (ej: 1.0.0 -> 1.0.1)
        run: npm version patch -m "chore(release): v%s [skip ci]"

      - name: Subir cambios de versión y Tags a GitHub
        run: |
          git push origin tooling --follow-tags

      - name: Publicar en GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
